driver:
  kind: ebpf
falcosidekick:
  enabled: true
  replicaCount: 1
  webui:
    enabled: true
    replicaCount: 1
    ttl: 1d
    disableauth: true
    service:
      type: NodePort
  config:
    webhook:
      address: "http://webhook/"
customRules:
  rob.yaml: |-
    - rule: do_not_tcpdump
      desc: warn when tcpdump is executed
      condition: >
         proc.is_exe_upper_layer=true and proc.name = "tcpdump" and container
      output: >
        (user=%user.name container_id=%container.id container_name=%container.name shell=%proc.name parent=%proc.pname cmdline=%proc.cmdline)    
      priority: WARNING