apiVersion: apps/v1
kind: Deployment
metadata:
  name: falco-webhook
  namespace: falco
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
        - name: webhook
          image: ghcr.io/robkenis/java-weekend-2023/webhook:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              name: http