apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadtest
  namespace: loadtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadtest
  template:
    metadata:
      labels:
        app: loadtest
        allow-ingress-to: nginx
    spec:
      containers:
        - name: loadtest
          image: busybox
          command: ["/bin/sh", "-c", "while true; do wget -O- http://nginx.rob.svc.cluster.local; sleep 10;done"]
